source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.7.3"
gem "rails", "~> 6.1.3"
gem "puma", "~> 4.3.5"

gem "activeadmin", "~> 2.9.0"
gem "acts_as_tree"
gem "aws-sdk-s3"
gem "bcrypt"
gem "bootsnap", require: false
gem "cancancan"
gem "country_select"
gem "data_migrate", "~> 6.6"
gem "devise"
gem "devise_invitable"
gem "discard"
gem "friendly_id", "~> 5.4"
gem "haml-rails"
gem "image_processing"
gem "jbuilder"
gem "kaminari"
gem "paperclip"
gem "pg"
gem "phony_rails"
gem "pundit"
gem "ranked-model"
gem "ransack"
gem "rb-readline"
gem "recaptcha"
gem "redcarpet"
gem "rollbar"
gem "sassc-rails"
gem "sidekiq"
gem "simple_form"
gem "shrine"
gem "stripe"
gem "stripe_event"
gem "turbolinks"
gem "webpacker"

group :development, :test do
  gem "byebug"
end

group :development do
  gem "web-console"
  gem "listen", ">= 3.0.5", "< 3.2"
  gem "spring"
  gem "spring-watcher-listen"
end

group :test do
  gem "capybara"
  gem "capybara-email"
  gem "database_cleaner"
  gem "email_spec"
  gem "factory_bot_rails"
  gem "faker"
  gem "fuubar"
  gem "rspec-rails"
  gem "rspec_junit_formatter", "0.2.3"
  gem "selenium-webdriver"
  gem "shoulda-matchers"
  gem "timecop"
  gem "vcr"
  gem "webdrivers"
  gem "webmock"
end
