source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.7.3"
gem "rails", "~> 6.1"
gem "puma", "~> 5.5"

gem "activeadmin", "~> 2.9"
gem "acts_as_tree", "~> 2.9"
gem "aws-sdk-s3", "~> 1.109"
gem "bcrypt", "~> 3.1"
gem "bootsnap", "~> 1.9", require: false
gem "cancancan", "~> 3.3"
gem "country_select", "~> 6.0"
gem "data_migrate", "~> 6.8"
gem "devise", "~> 4.8"
gem "devise_invitable", "~> 2.0"
gem "discard", "~> 1.2"
gem "friendly_id", "~> 5.4"
gem "haml-rails", "~> 2.0"
gem "image_processing", "~> 1.12"
gem "jbuilder", "~> 2.11"
gem "kaminari", "~> 1.2"
gem "paperclip", "~> 6.1"
gem "pg", "~> 1.2"
gem "phony_rails", "~> 0.15"
gem "pundit", "~> 2.1"
gem "ranked-model", "~> 0.4"
gem "ransack", "~> 2.4"
gem "rb-readline", "~> 0.5"
gem "recaptcha", "~> 5.8"
gem "redcarpet", "~> 3.5"
gem "rollbar", "~> 3.3"
gem "sassc-rails", "~> 2.1"
gem "sidekiq", "~> 6.3"
gem "simple_form", "~> 5.1"
gem "shrine", "~> 3.4"
gem "stripe", "~> 5.41"
gem "stripe_event", "~> 2.3"
gem "turbolinks", "~> 5.2"
gem "webpacker", "~> 5.4"

group :development, :test do
  gem "byebug", "~> 11.1"
end

group :development do
  gem "web-console", "~> 4.2"
  gem "listen", "~> 3.1", "< 3.2"
  gem "spring", "~> 2.1"
  gem "spring-watcher-listen", "~> 2.0"
end

group :test do
  gem "capybara", "~> 3.36"
  gem "capybara-email", "~> 3.0"
  gem "database_cleaner", "~> 2.0"
  gem "email_spec", "~> 2.2"
  gem "factory_bot_rails", "~> 6.2"
  gem "faker", "~> 2.19"
  gem "fuubar", "~> 2.5"
  gem "rspec-rails", "~> 5.0"
  gem "rspec_junit_formatter", "~> 0.2"
  gem "selenium-webdriver", "~> 4.1"
  gem "shoulda-matchers", "~> 5.0"
  gem "timecop", "~> 0.9"
  gem "vcr", "~> 6.0"
  gem "webdrivers", "~> 5.0"
  gem "webmock", "~> 3.14"
end
